name: "PR title replace"
description: "Replaces string in PR title"
inputs:
  github_token:
    description: "The GITHUB_TOKEN secret"
    required: true
  find:
    description: "What to find (could be a regex)"
    default: ""
  replace:
    description: "Replace found part with"
    default: ""
outputs:
  title:
    description: "New title"
runs:
  using: "node12"
  main: "index.js"
